version: "3.9"
services:
  backend:
    container_name: backend
    image: backend:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/test_spring
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=sasa
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: test_spring